version: 0.0
os: linux

files:
  - source: /
    destination: /opt/super-app
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/chmod.sh
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 600
      runas: root
