version: "3.9"

services:
  db:
    image: mysql:8.0.28
    container_name: superapp-mysql
    environment:
      MYSQL_DATABASE: "super_app"
      MYSQL_ROOT_PASSWORD: "password"
      # למקרה שתרצה משתמש לא-רוט:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 10

  node:
    build:
      context: ./node
    container_name: superapp-node
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: "super_app"
      DB_USER: "root"
      DB_PASSWORD: "password"
      PORT: "3000"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  php:
    build:
      context: ./php
    container_name: superapp-php
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: "super_app"
      DB_USER: "root"
      DB_PASSWORD: "password"
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
