name: docker-publish
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Node image
        uses: docker/build-push-action@v6
        with:
          context: ./node
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/super-app-node:latest,${{ secrets.DOCKERHUB_USERNAME }}/super-app-node:${{ github.sha }}

      - name: Build and push PHP image
        uses: docker/build-push-action@v6
        with:
          context: ./php
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/super-app-php:latest,${{ secrets.DOCKERHUB_USERNAME }}/super-app-php:${{ github.sha }}
