name: ghcr-publish
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Node to GHCR
        uses: docker/build-push-action@v6
        with:
          context: ./node
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/super-app-node:latest,ghcr.io/${{ github.repository_owner }}/super-app-node:${{ github.sha }}

      - name: Build & push PHP to GHCR
        uses: docker/build-push-action@v6
        with:
          context: ./php
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/super-app-php:latest,ghcr.io/${{ github.repository_owner }}/super-app-php:${{ github.sha }}
